apiVersion: batch/v1
kind: Job
metadata:
  name: bookinfo-siege
  namespace: load
spec:
  template:
    spec:
      containers:
      - name: siege
        image: rippmn/siege
        command: ["siege","http://INGRESSIP/productpage"]
      restartPolicy: OnFailure
  backoffLimit: 4
