apiVersion: batch/v1
kind: Job
metadata:
  name: load-app
  namespace: load
spec:
  template:
    spec:
      containers:
      - name: load-app
        image: rippmn/siege
        command: ["siege","-d","2",  "http://hello-load-app.default.INGRESS_IP.xip.io"]
      restartPolicy: OnFailure
  backoffLimit: 4
